version: '3.4'
services:
  netbox:
     restart: unless-stopped
     ports:
      - 8000:8080
  netbox-worker:
   restart: unless-stopped
  postgres:
   restart: unless-stopped
  redis:
   restart: unless-stopped
  redis-cache:
   restart: unless-stopped
